name: Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: build ${{ github.ref_name }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
          
      - name: Log in to Docker Hub
        run: |
          docker build -t daniyal439/notybot .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push
          
