name: Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: 'read'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: build ${{ github.ref_name }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: properties from ${{ inputs.image_directory }}
        shell: bash
        working-directory: ${{ inputs.image_directory }}
        id: properties
        run: |
          echo "::set-output name=tag::$(sed -n -e '/^tag/ s/.*\: *//p' versionInfo)"
          echo "::set-output name=labels::$(sed -n -e '/^labels/ s/.*\: *//p' versionInfo)"
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.properties.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
